name: Test Python

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'api/**'
    branches:
      - main

jobs:
  test-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0.21'
          mysql database: 'spi_data'
          mysql root password: 'testpassword'

      - name: Install Dependencies
        run: |
          cd api
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          pip install -e .
          pip list

      - name: Migrate database
        env:
          DATABASE_URL: "mysql://root:testpassword@127.0.0.1:3306/spi_data"
        run: |
          curl -fsSL -o ./dbmate https://github.com/amacneil/dbmate/releases/latest/download/dbmate-linux-amd64
          chmod +x ./dbmate
          ./dbmate --wait up

      - name: Test
        run: |
          pytest api/solarperformanceinsight_api --cov=solarperformanceinsight_api --cov-report=term-missing --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          flags: python
          files: coverage.xml
          fail_ci_if_error: true
        if: ${{ always() }}

  lint-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable

  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Dependencies
        run: |
          cd api
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          pip install -e .
          pip list

      - name: Run mypy
        run: mypy api/solarperformanceinsight_api
